INSERT INTO DOGS(id, name, breed, origin) VALUES (1, 'dog1','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (2, 'dog2','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (3, 'dog3','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (4, 'dog4','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (5, 'dog5','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (6, 'dog6','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (7, 'dog7','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (8, 'dog8','yellow','china');
INSERT INTO DOGS(id, name, breed, origin) VALUES (9, 'dog9','yellow','china');